### ISSUE TITLE
About M_t

### ISSUE THREAD

**Issue by suyukun666** [ZHANGDONG-NJUST/CONTA#12]
Nice job!  Here is my question about the main operation for Eq(3).
(1) In which py file do you operate for Eq(3)? 
(2) As I can see, in "segmentation/tools/m_t.py",  where is the "cfg.DIC_FILE" and "cfg.PRIOR_PROB"?

**Comment by ZHANGDONG-NJUST** [comment]
@suyukun666  Thanks for your attention. 1. Eq(3) is performed in m_t.py. 2. "cfg.DIC_FILE" and "cfg.PRIOR_PROB"  denotes the confounder set C and P(c), respectively. The confounder set can be obtained via computing the class-specific average segmentation-mask, and P(c) is set as the uniform 1/n. where n is the class number.

**Comment by cyy5358** [comment]
> @suyukun666 Thanks for your attention. 1. Eq(3) is performed in m_t.py. 2. "cfg.DIC_FILE" and "cfg.PRIOR_PROB" denotes the confounder set C and P(c), respectively. The confounder set can be obtained via computing the class-specific average segmentation-mask, and P(c) is set as the uniform 1/n. where n is the class number.

Hi, Thank you for your great work!
You mentioned that Eq(3) is performed in m_t.py. I don't find any .py code importing m_t. Do I need run m_t.py manually ?
@ZHANGDONG-NJUST

**Comment by ZHANGDONG-NJUST** [comment]
@cyy5358 m_t  is used for the new round of classification. You can add it manually to make it work.

**Comment by Welllee12366** [comment]
> @cyy5358 m_t is used for the new round of classification. You can add it manually to make it work.

Sorry, as a beginner, I don't know which classifier this file needs to be added to. If it is convenient for you, I'm looking forward to your more detailed answer to this question. Thank you

**Comment by ZHANGDONG-NJUST** [comment]
@Welllee12366  If you don’t mind, you can send me an email at dongzhang@njust.edu.cn. I can give you my phone number, discussion on the phone may be more efficient
