### ISSUE TITLE
MISS of average mask

### ISSUE THREAD

**Issue by DepueeDome** [ZHANGDONG-NJUST/CONTA#13]
Hi, thanks for your brilliant work. 
I try to re-run your project, but i can't found the code for calculating the average segmentation mask as well as the usage of m_t.py in irn project, did i missed any information?

**Comment by ZHANGDONG-NJUST** [comment]
@DepueeDome  Thank you for your attention. This part of the script code needs to be prepared by yourself.

**Comment by DepueeDome** [comment]
> @DepueeDome Thank you for your attention. This part of the script code needs to be prepared by yourself.

Thanks for your reply! may i verify some parameters in m_t.py  with you here?

1.According to your paper, Eq. 3, X_m denotes the segmentation mask (h*w) and c_i is (h*w*1), 
therefore, should both the embedding_size and the representation_size change to 1 in m_t.py?

**Comment by DepueeDome** [comment]
> @DepueeDome Thank you for your attention. This part of the script code needs to be prepared by yourself.

Thanks for your reply! may i verify some parameters in m_t.py  with you here?

1.According to your paper, Eq. 3, X_m denotes the segmentation mask (h*w) and c_i is (h*w*1), 
therefore, should both the embedding_size and the representation_size change to 1 in m_t.py?

**Comment by ZHANGDONG-NJUST** [comment]
@DepueeDome Both segmentation mask and c_i denote hw*1, and the embedding size (W_1 and W_2) is n*hw.

**Comment by DepueeDome** [comment]
> @DepueeDome Both segmentation mask and c_i denote hw_1, and the embedding size (W_1 and W_2) is n_hw.

So the output of M_t is (hw1), where h and w determine by the feature map M_t concatenate to, and i right?

**Comment by ZHANGDONG-NJUST** [comment]
@DepueeDome  Yes, you are right.

**Comment by DepueeDome** [comment]
> @DepueeDome Yes, you are right.

Thanks a lot!

**Comment by pkmandke** [comment]
> @DepueeDome Both segmentation mask and c_i denote hw1, and the embedding size (W_1 and W_2) is nhw.

@ZHANGDONG-NJUST Could you please elaborate a little further on this.
If I understand correctly, both X_m and c_i are of dim *hw x 1* and W_1 and W_2 are *n x hw*. Then, the term inside the softmax (in Eq (3)) would have a dimension of *1 x 1*. What exactly is the dimension of alpha_i? Is the term inside the softmax being computed for all *n* segmentation masks and then the softmax is applied over these *n* scores?

Thanks!

**Comment by ZHANGDONG-NJUST** [comment]
@pkmandke   1. alpha_i is a scalar, so it has a dimension of 1 x 1; 2. softmax is only applied over n scores.
