### ISSUE TITLE
Step 4 compute M_{t+1}

### ISSUE THREAD

**Issue by tuffr5** [ZHANGDONG-NJUST/CONTA#16]
Thanks for sharing the code. By referring to Figure 4, I thought the model was end_to_end. But I am not able to find any evidence. It seems like steps are separated. In addition, can you point where do you calculate step 4?

**Comment by ZHANGDONG-NJUST** [comment]
Thanks your your attention. The model is not e-2-e training. Step4 is in segmentation.m_t.py
