### ISSUE TITLE
how to do causal intervention

### ISSUE THREAD

**Issue by JohnDreamer** [ZHANGDONG-NJUST/CONTA#18]
Hi, it is a great work! But I'm a little confused about your code. As you mentioned in your paper, you have done a causal intervention by using average segmentation masks of different objects. However, I have checked out all your codes, I didn't found any code which is used to introduce average segmentation masks to do a causal intervention. And there is also no code for loading average segmentation masks. Could you please point out where you deal with this? It will be very appreciated that you answer this question!

**Comment by ZHANGDONG-NJUST** [comment]
@JohnDreamer   Thanks for your attention and sorry for the confusion. Intervention is performed in a new round classification. Before this, you should do two things: 1) creating a confounder set via the segmentation mask; 2) calculating  m_{t+1} for each training image via Eq.(3)

**Comment by yongduosui** [comment]
@dongzhang89 I think these two things is the main contribution of your paper. I hope you can release all these code, thanks.
