### ISSUE TITLE
Why m_t.py is not imported by any other py files? It seems the code is not complete?

### ISSUE THREAD

**Issue by LeeSureman** [ZHANGDONG-NJUST/CONTA#19]
It seems the code is not complete? Can you release the code thas can be directly run and reflect the computation of the paper (eq3 )?

**Comment by HHHedo** [comment]
I have the same question.

**Comment by LeeSureman** [comment]
> I have the same question.

Thank you for your reply. I thought maybe I misunderstood the code and now you dispell my doubt.

**Comment by ZHANGDONG-NJUST** [comment]
@LeeSureman @HHHedo  Thanks for your attention and sorry for the confusion.  The training process of the whole model consists of several separate steps. This repository contains most of the main codes, and the calculation step for Eq.(3) is in m_t. Before this, you should prepare two things: 1) creating a confounder set via the segmentation mask; 2) calculating m_{t+1} for each training image. If you have more questions during the implementation, please email me to dongzhang@njust.edu.cn. Thank you !

**Comment by LeeSureman** [comment]
Why can't you release the complete code?

**Comment by ZHANGDONG-NJUST** [comment]
@LeeSureman  What exactly do you mean? All tools I used are in this repository
