### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by LeiZhenzhen220** [ZHANGDONG-NJUST/CONTA#2]
Import Error: cannot import name 'get_dataset'
Import Error: cannot import name 'DeepLabV2_ResNet101_MSC'

**Comment by ZHANGDONG-NJUST** [comment]
Thanks for attention. I guess this is due to the environment configuration.  Would you mind show more about your environment specifics ?

**Comment by LeiZhenzhen220** [comment]
pytorch :1.5.1

**Comment by LeiZhenzhen220** [comment]
python 3.6.10, pytorch 1.5.1,torchvision 0.6.1,

**Comment by ZHANGDONG-NJUST** [comment]
Please refer to the requirements.txt, thanks !

**Comment by chanhal** [comment]
Hi, where are the definitions of "get_dataset" and "get_dataset" in your repo ?
Sorry, I couldn't find them.

**Comment by ZHANGDONG-NJUST** [comment]
@chanhal   The bug has been fixed, please try again.
