### ISSUE TITLE
The apply of your work?

### ISSUE THREAD

**Issue by zbf1991** [ZHANGDONG-NJUST/CONTA#3]
I noticed the implementation of your work is mainly in  \segmentation\tools\m_t. But I cannot find which file applies them in the project. Could you please tell me the actual use in the project of your implementation such as Eq2 and Eq3? Thanks.

**Comment by ZHANGDONG-NJUST** [comment]
Thanks for your attention. 1) The implementation of Eq.(2) is a standard multi-label soft-margin classification loss with m_t which is concatenated into the backbone; 2)  Eq.(3) is used to calculate m_t, which is based on a segmantation mask and the confounder  set.  I will update more detailed codes later. For the implementation details, you can refer to our paper.

**Comment by TyroneLi** [comment]
> Thanks for your attention. 1) The implementation of Eq.(2) is a standard multi-label soft-margin classification loss with m_t which is concatenated into the backbone; 2) Eq.(3) is used to calculate m_t, which is based on a segmantation mask and the confounder set. I will update more detailed codes later. For the implementation details, you can refer to our paper.

Actually, I could not get your points yet. I found inside pseudo code, there're nothing different between IRNet and your implementation code, and for segmentation code, I cannot seed that the code in tools/ folder was imported by main part code.Could you provide more details? Thanks

**Comment by ZHANGDONG-NJUST** [comment]
@TyroneLi Sorry for the confusion. The initialized procedure for generating pseudo-mask is the same as the one in IRNet. The point of CONTA is in segmentation/tools/m_t.py. Before conputing m_t, you need a confounder set and a segmentation mask for each training image. You can refer to Step.4 in Section 3.2. More detailed codes will be released after the CVPR deadline.

**Comment by TyroneLi** [comment]
> @TyroneLi Sorry for the confusion. The initialized procedure for generating pseudo-mask is the same as the one in IRNet. The point of CONTA is in segmentation/tools/m_t.py. Before conputing m_t, you need a confounder set and a segmentation mask for each training image. You can refer to Step.4 in Section 3.2. More detailed codes will be released after the CVPR deadline.

OK, I see. So that means generating pseudo mask procedure is the same as IRNet in your paper, and CONTA implementation is included in training segmentation procedure, am I right? By the way, I experimented with same method, and I got higher mIoU than resnet50 baseline in eval_cam procedure, that means using my method generated cam is better than original baseline, but after IRNet training, I got a lower mIoU in final eval_sem_seg, how do you think this issue? hah thanks for your discussion.

**Comment by ZHANGDONG-NJUST** [comment]
@TyroneLi  CONTA is implemented after the segmentation model. Usually, better CAM indicates better pseudo-mask as well as better segmentation result on the val set. I guess the reason may be hidden in CAM expansion. I suggest you can print the pasudo-masks generated by both methods and make a comparison. You will get the answer. Besides, my experience is that result on AffinityNet sometimes better than the one on IRNet, that depends on the specific quality of CAMs.

**Comment by TyroneLi** [comment]
> @TyroneLi CONTA is implemented after the segmentation model. Usually, better CAM indicates better pseudo-mask as well as better segmentation result on the val set. I guess the reason may be hidden in CAM expansion. I suggest you can print the pasudo-masks generated by both methods and make a comparison. You will get the answer. Besides, my experience is that result on AffinityNet sometimes better than the one on IRNet, that depends on the specific quality of CAMs.

Yes, I found that though my cam quality is better than original baseline, generated ir_label is worse after CRF post-processing. And that made a bad effect to IRNet training. Maybe I should try AffinityNet, but AffinityNet now just support resnet38 or vgg but not resnet50, and that may remain a long experiment step.
