### ISSUE TITLE
In make_sem_seg_labels.py, how to apply crf postprocessing at final result pseudo mask image?

### ISSUE THREAD

**Issue by TyroneLi** [ZHANGDONG-NJUST/CONTA#7]

**Comment by TyroneLi** [comment]
> _No description provided._

The fully-connected CRF [27] was used to refine CAM, pseudo-mask, and
segmentation mask with the default parameters given in the original code. The hard threshold
parameter for CAM was set to 16 by default and changed to 4 and 24 to amplify and weaken the
background activation, respectively. The radius γ that limits the search space of pairs was set to 10
when training, and reduced to 5 at inference (conservative propagation in inference). The number
of random walk iterations t was fixed to 256. The hyper-parameter β in the Hadamard power of the
affinity matrix was set to 10.
For this description in your paper, but I cannot refer to this implementation in your repro? Could you point that out?

**Comment by ZHANGDONG-NJUST** [comment]
@TyroneLi  Thanks for your queation. 1) The CRF code has been released in pseudo_mask/tools/CRF.py, you can use it to refine the corresponding masks. 2) all the training hyper-parameters for IRNet are in run_samle.py.
