### ISSUE TITLE
ImportError: cannot import name 'DeepLabV2_ResNet101_MSC' from 'libs.models' (unknown location)"

### ISSUE THREAD

**Issue by Unrealluver** [ZHANGDONG-NJUST/CONTA#8]
Greetings,

I met the error :

"Traceback (most recent call last):
  File "/home/CONTA/segmentation/main.py", line 22, in <module>
    from libs.models import DeepLabV2_ResNet101_MSC
ImportError: cannot import name 'DeepLabV2_ResNet101_MSC' from 'libs.models' (unknown location)"

I found this method in the whole project but still cannot find it, could you please give me some hint to solve this?

**Comment by ZHANGDONG-NJUST** [comment]
@Unrealluver  Thanks for your report. The problem has been addressed, please try again.
